/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Evaluacion;
import model.InstanciaEvaluacion;

/**
 *
 * @author KEDAC
 */
public class JDlgModificarPorcentaje extends javax.swing.JDialog {

    private ArrayList<Evaluacion> evaluaciones;
    private ArrayList<InstanciaEvaluacion> instancias;
    DefaultComboBoxModel modelEvaluaciones;
    DefaultComboBoxModel modelInstacias;
    private boolean esEvaluacion;
    /**
     * Creates new form JDlgModificarPorcentaje
     */
    public JDlgModificarPorcentaje(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/view/source/favicon.ico")).getImage());
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno = new ImageIcon(this.getClass().getResource("/view/source/fondo.jpg"));
        JLabel fondo = new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight()); 
    }

    public void setEvaluaciones(ArrayList<Evaluacion> evaluaciones) {
        this.evaluaciones = evaluaciones;
    }   
    
    public void setInstancias(ArrayList<InstanciaEvaluacion> instancias) {
        this.instancias = instancias;
    }      
    
    public ArrayList<Evaluacion> getEvaluaciones() {
        return this.evaluaciones;
    }
    
    public ArrayList<InstanciaEvaluacion> getInstancias() {
        return this.instancias;
    }    
    
    public void esEvaluacion() {
        this.esEvaluacion = true;
    }
    
    public void esInstancia() {
        this.esEvaluacion = false;
    }    
    
    public void cargarEvaluaciones() {      
        modelEvaluaciones = new DefaultComboBoxModel();
        this.modelEvaluaciones.addElement("");  
        for (int i = 0; i < evaluaciones.size(); i++) {
            modelEvaluaciones.addElement(evaluaciones.get(i).getTipoEvaluacion());
        }
        this.jCB.setModel(modelEvaluaciones);        
    }
    
    public void cargarInstancias() {      
        modelInstacias = new DefaultComboBoxModel();
        this.modelInstacias.addElement("");  
        for (int i = 0; i < instancias.size(); i++) {
            modelInstacias.addElement(instancias.get(i).getDescripcion());
        }
        this.jCB.setModel(modelInstacias);        
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCB = new javax.swing.JComboBox();
        jTxtPorcentaje = new javax.swing.JTextField();
        jBtnModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificación de Porcentaje");
        setResizable(false);

        jCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jBtnModificar.setText("Modificar");
        jBtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTxtPorcentaje)
                    .addComponent(jBtnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTxtPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnModificar)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModificarActionPerformed
        if (this.jCB.getSelectedIndex() != 0) {
            if (esEvaluacion) {
                for (Evaluacion evaluacion : evaluaciones) {       
                    try {
                        if (evaluacion.getTipoEvaluacion().equals(this.jCB.getSelectedItem().toString())) {
                            float porcentaje = Float.parseFloat(this.jTxtPorcentaje.getText());
                            if (porcentaje >= 0 && porcentaje <= 100) {
                                evaluacion.setPorcentaje(Float.parseFloat(this.jTxtPorcentaje.getText()));
                                this.setVisible(false);
                            }                       
                        } 
                    }
                    catch (Exception e) {
                        JOptionPane.showMessageDialog(rootPane, "Porcentaje inválido!"); 
                        System.out.println(e);
                    }
                }
            }
            else {
                 for (InstanciaEvaluacion instancia : instancias) {       
                    try {
                        if (instancia.getDescripcion().equals(this.jCB.getSelectedItem().toString())) {
                            float valor = Float.parseFloat(this.jTxtPorcentaje.getText());
                            if (valor >= 0 && valor <= 100) {
                                instancia.setValor(Float.parseFloat(this.jTxtPorcentaje.getText()));
                                this.setVisible(false);
                            }                       
                        } 
                    }
                    catch (Exception e) {
                        JOptionPane.showMessageDialog(rootPane, "Valor inválido!"); 
                        System.out.println(e);
                    }
                }           
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Falta información!");
        }
    }//GEN-LAST:event_jBtnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgModificarPorcentaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgModificarPorcentaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgModificarPorcentaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgModificarPorcentaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgModificarPorcentaje dialog = new JDlgModificarPorcentaje(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnModificar;
    private javax.swing.JComboBox jCB;
    private javax.swing.JTextField jTxtPorcentaje;
    // End of variables declaration//GEN-END:variables
}
