/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.InstanciaEvaluacion;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Esteban
 */
public class JDlgInstanciaFija extends javax.swing.JDialog {

    /**
     * Creates new form JDLIntanciasFijas
     */
    
    DefaultTableModel tablaInstancias;
    private InstanciaEvaluacion instancia;
    private ArrayList<InstanciaEvaluacion> instancias;
    
    public JDlgInstanciaFija(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        instancias = new ArrayList<>();
        tablaInstancias = new DefaultTableModel();
        tablaInstancias.addColumn("Descripción");
        tablaInstancias.addColumn("Fecha");
        tablaInstancias.addColumn("Valor");   
        this.jTblInstancias.setModel(tablaInstancias);
        setIconImage(new ImageIcon(getClass().getResource("/view/source/favicon.ico")).getImage());
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno = new ImageIcon(this.getClass().getResource("/view/source/fondo.jpg"));
        JLabel fondo = new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight()); 
    }
    
    public ArrayList<InstanciaEvaluacion> getInstancias() {
        return this.instancias;
    }
    
    public void setInstancias(ArrayList<InstanciaEvaluacion> instancias) {
        this.instancias = instancias;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtDescripcion = new javax.swing.JTextField();
        TxtFecha = new javax.swing.JTextField();
        TxtPorcentaje = new javax.swing.JTextField();
        jBtnAgregarInstancia = new javax.swing.JButton();
        jBtnAceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblInstancias = new javax.swing.JTable();
        jBtnModificarPorcentaje = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Instancia Fija");
        setResizable(false);

        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Descripción:");

        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Fecha:");

        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Porcentaje:");

        TxtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDescripcionActionPerformed(evt);
            }
        });

        jBtnAgregarInstancia.setText("Agregar Instancia");
        jBtnAgregarInstancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarInstanciaActionPerformed(evt);
            }
        });

        jBtnAceptar.setText("Aceptar");
        jBtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAceptarActionPerformed(evt);
            }
        });

        jTblInstancias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTblInstancias.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(jTblInstancias);

        jBtnModificarPorcentaje.setText("Modificar Porcentaje");
        jBtnModificarPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnModificarPorcentajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBtnAgregarInstancia, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jBtnModificarPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtDescripcion)
                    .addComponent(TxtFecha)
                    .addComponent(TxtPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAgregarInstancia)
                    .addComponent(jBtnAceptar)
                    .addComponent(jBtnModificarPorcentaje))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDescripcionActionPerformed

    private void jBtnAgregarInstanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarInstanciaActionPerformed
        if (!this.TxtDescripcion.getText().isEmpty() && 
                !this.TxtFecha.getText().isEmpty() && 
                !this.TxtPorcentaje.getText().isEmpty()) {
            try {
                float porcentaje = Float.parseFloat(this.TxtPorcentaje.getText());
                if (porcentaje >= 0 && porcentaje <= 100) {
                    boolean existe = false;
                    for (InstanciaEvaluacion instanciaE : instancias) {
                        if (instanciaE.getDescripcion().equals(this.TxtDescripcion.getText())) {
                            existe = true;
                        }
                    }
                    if (!existe) {
                        instancia = new InstanciaEvaluacion(porcentaje, this.TxtDescripcion.getText(), this.TxtFecha.getText());
                        instancias.add(instancia);  

                        String []informacion = new String[4];
                        informacion[0] = instancia.getDescripcion();   
                        informacion[1] = instancia.getFecha();   
                        informacion[2] = instancia.getValor() + "%";      
                        this.tablaInstancias.addRow(informacion); 

                        this.TxtDescripcion.setText("");
                        this.TxtFecha.setText("");
                        this.TxtPorcentaje.setText("");
                    } 
                    else {
                        JOptionPane.showMessageDialog(rootPane, "Instancia previamente creada!");                            
                    }
                }
                else {
                    JOptionPane.showMessageDialog(rootPane, "Porcentaje inválido!");                    
                }
            } 
            catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Porcentaje inválido!");    
                System.out.println(e);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Falta información!");
        }        
    }//GEN-LAST:event_jBtnAgregarInstanciaActionPerformed

    private void jBtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAceptarActionPerformed
        float porcentaje = 0;
        for (InstanciaEvaluacion instancia : instancias) {
            porcentaje += instancia.getValor();
        }
        if (porcentaje == 100) {
            this.setVisible(false);        
        }
        else {
            JOptionPane.showMessageDialog(rootPane, "El porcentaje debe de sumar 100!");            
        }
    }//GEN-LAST:event_jBtnAceptarActionPerformed

    private void jBtnModificarPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModificarPorcentajeActionPerformed
        JDlgModificarPorcentaje modificar = new JDlgModificarPorcentaje(null, true);
        modificar.setInstancias(this.instancias);
        modificar.esInstancia();
        modificar.cargarInstancias();
        modificar.setLocationRelativeTo(null);
        modificar.setVisible(true);
        this.instancias = modificar.getInstancias();
        for (int i = 0; i < instancias.size(); i++) {
            if (this.tablaInstancias.getValueAt(i, 0).equals(instancias.get(i).getDescripcion())) {
                this.tablaInstancias.setValueAt(instancias.get(i).getValor()+ "%", i, 2);               
            }            
        }
    }//GEN-LAST:event_jBtnModificarPorcentajeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgInstanciaFija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgInstanciaFija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgInstanciaFija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgInstanciaFija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgInstanciaFija dialog = new JDlgInstanciaFija(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtDescripcion;
    private javax.swing.JTextField TxtFecha;
    private javax.swing.JTextField TxtPorcentaje;
    private javax.swing.JButton jBtnAceptar;
    private javax.swing.JButton jBtnAgregarInstancia;
    private javax.swing.JButton jBtnModificarPorcentaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblInstancias;
    // End of variables declaration//GEN-END:variables
}
