/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.sql.EvaluacionGrupo;
import model.sql.Miembro;

/**
 *
 * @author KEDAC
 */
public class JDlgRegistro extends javax.swing.JDialog {

    private String codigoGrupo;
    private ArrayList<String> evaluaciones;
    DefaultComboBoxModel modelEstudiantes;
    DefaultComboBoxModel modelEvaluaciones;

    /**
     * Creates new form JDlgRegistro
     */
    public JDlgRegistro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/view/source/favicon.ico")).getImage());
        ((JPanel) getContentPane()).setOpaque(false);
        ImageIcon uno = new ImageIcon(this.getClass().getResource("/view/source/fondo.jpg"));
        JLabel fondo = new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo, JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0, 0, uno.getIconWidth(), uno.getIconHeight());
    }

    public void setCodigoGrupo(String pCodigo) throws SQLException {
        this.codigoGrupo = pCodigo;
    }

    public void cargarEstudiantes() throws SQLException {
        modelEstudiantes = new DefaultComboBoxModel();
        this.modelEstudiantes.addElement("");
        ArrayList<String> estudiantes = Miembro.getInstance().miembrosGrupo(codigoGrupo);
        for (String estudiante : estudiantes) {
            this.modelEstudiantes.addElement(estudiante);
        }
        this.jCBEstudiantes.setModel(modelEstudiantes);
    }

    public void cargarEvaluaciones() throws SQLException {
        modelEvaluaciones = new DefaultComboBoxModel();
        this.modelEvaluaciones.addElement("");
        this.evaluaciones = EvaluacionGrupo.getInstance().evaluacionGrupo(codigoGrupo);
        for (int i = 0; i < evaluaciones.size(); i += 4) {
            modelEvaluaciones.addElement(evaluaciones.get(i));
        }
        this.jCBEvaluaciones.setModel(modelEvaluaciones);
    }
    
    public void inicializarNotas() throws SQLException {
        ArrayList<String> miembros = Miembro.getInstance().miembrosGrupo(this.codigoGrupo);
        for (String miembro : miembros) {
            this.evaluaciones = EvaluacionGrupo.getInstance().evaluacionGrupo(codigoGrupo);
            for (int i = 0; i < evaluaciones.size(); i += 4) {                
                EvaluacionGrupo.getInstance().inicializarNotas(miembro, codigoGrupo, evaluaciones.get(i));
            }        
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCBEvaluaciones = new javax.swing.JComboBox();
        jBtnRegistrar = new javax.swing.JButton();
        jCBEstudiantes = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Notas");
        setResizable(false);

        jCBEvaluaciones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jBtnRegistrar.setText("Registrar");
        jBtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegistrarActionPerformed(evt);
            }
        });

        jCBEstudiantes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jCBEvaluaciones, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCBEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jBtnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jCBEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCBEvaluaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnRegistrar)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegistrarActionPerformed
        if (this.jCBEvaluaciones.getSelectedIndex() != 0 && this.jCBEstudiantes.getSelectedIndex() != 0) {
            for (int i = 0; i < this.evaluaciones.size(); i += 4) {
                if (this.evaluaciones.get(i).equals(this.jCBEvaluaciones.getSelectedItem().toString())) {
                    if (this.evaluaciones.get(i + 2).equals("Fija")) {
                        this.setVisible(false);
                        JDlgRegistroIF registroIF = new JDlgRegistroIF(null, true);
                        try {                            
                            registroIF.setCodigoGrupo(this.codigoGrupo);
                            registroIF.setEvaluacion(this.jCBEvaluaciones.getSelectedItem().toString());
                            registroIF.setEstudiante(this.jCBEstudiantes.getSelectedItem().toString());
                            registroIF.cargarInstancias();
                            registroIF.cargarComboBoxInstancias();
                            registroIF.cargarTablaInstancias();
                        } catch (SQLException ex) {
                            Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        registroIF.setLocationRelativeTo(null);
                        registroIF.setVisible(true);                        
                        this.jCBEvaluaciones.setSelectedIndex(0);
                        this.jCBEstudiantes.setSelectedIndex(0);
                        this.setVisible(true);                        
                    } else {
                        this.setVisible(false);
                        JDlgRegistroIV registroIV = new JDlgRegistroIV(null, true);
                        try {
                            registroIV.setCodigoGrupo(this.codigoGrupo);
                            registroIV.setEvaluacion(this.jCBEvaluaciones.getSelectedItem().toString());
                            registroIV.setEstudiante(this.jCBEstudiantes.getSelectedItem().toString());   
                            registroIV.cargarInstancias();     
                            registroIV.cargarTablaInstancias();                    
                        } catch (SQLException ex) {
                            Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        registroIV.setLocationRelativeTo(null);
                        registroIV.setVisible(true);            
                        this.jCBEvaluaciones.setSelectedIndex(0);
                        this.jCBEstudiantes.setSelectedIndex(0);
                        this.setVisible(true); 
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Falta información!");
        }
    }//GEN-LAST:event_jBtnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgRegistro dialog = new JDlgRegistro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnRegistrar;
    private javax.swing.JComboBox jCBEstudiantes;
    private javax.swing.JComboBox jCBEvaluaciones;
    // End of variables declaration//GEN-END:variables
}
