/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Evaluacion;
import model.sql.Grupo;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author usuario
 */
public class JDlgEvaluacion extends javax.swing.JDialog {

    DefaultComboBoxModel modeltipoEvaluaciones;
    DefaultComboBoxModel tipoInstancia;
    private String codigoGrupo;
    private Evaluacion evaluacion;

    public JDlgEvaluacion(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tipoInstancia = new DefaultComboBoxModel();
        this.tipoInstancia.addElement("");
        this.tipoInstancia.addElement("Fija");
        this.tipoInstancia.addElement("Variable");
        this.CboInstancia.setModel(tipoInstancia);   
        this.evaluacion = null;
        setIconImage(new ImageIcon(getClass().getResource("/view/source/favicon.ico")).getImage());
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno = new ImageIcon(this.getClass().getResource("/view/source/fondo.jpg"));
        JLabel fondo = new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight()); 
    }

    public void setCodigoGrupo(String pCodigo) throws SQLException {
        this.codigoGrupo = pCodigo;
    }
    
    public Evaluacion getEvaluacion() {
        return this.evaluacion;
    }

    public void cargarTipoEvaluaciones() throws SQLException {
        this.modeltipoEvaluaciones = new DefaultComboBoxModel();
        this.modeltipoEvaluaciones.addElement("");
        ArrayList<String> tipoEvaluaciones = Grupo.getInstance().tiposEvaluaciones();
        for (String tipo : tipoEvaluaciones) {
            this.modeltipoEvaluaciones.addElement(tipo);
        }
        this.CboTipoEval.setModel(modeltipoEvaluaciones);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelTipoEval = new javax.swing.JLabel();
        CboTipoEval = new javax.swing.JComboBox();
        LabelPorcentaje = new javax.swing.JLabel();
        TxtPorcentaje = new javax.swing.JTextField();
        CboInstancia = new javax.swing.JComboBox();
        LabelTipoInstancia = new javax.swing.JLabel();
        BtnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Evaluación");
        setResizable(false);

        LabelTipoEval.setForeground(new java.awt.Color(240, 240, 240));
        LabelTipoEval.setText("Tipo de Evaluacion:");

        CboTipoEval.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        LabelPorcentaje.setForeground(new java.awt.Color(240, 240, 240));
        LabelPorcentaje.setText("Porcentaje Total:");

        CboInstancia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fija", "Variable" }));

        LabelTipoInstancia.setForeground(new java.awt.Color(240, 240, 240));
        LabelTipoInstancia.setText("Tipo de Instancia:");

        BtnAceptar.setText("Aceptar");
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelTipoEval)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelTipoInstancia, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LabelPorcentaje, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CboTipoEval, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtPorcentaje)
                            .addComponent(CboInstancia, 0, 168, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(BtnAceptar)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTipoEval)
                    .addComponent(CboTipoEval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPorcentaje)
                    .addComponent(TxtPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CboInstancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTipoInstancia))
                .addGap(34, 34, 34)
                .addComponent(BtnAceptar)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
        if (this.CboTipoEval.getSelectedIndex() != 0 && 
                this.CboInstancia.getSelectedIndex() != 0 &&
                !this.TxtPorcentaje.getText().isEmpty()) {
            try {
                float porcentaje = Float.parseFloat(this.TxtPorcentaje.getText());
                if (porcentaje >= 0 && porcentaje <= 100) {
                    if (this.CboInstancia.getSelectedItem().equals("Fija")) {
                        JDlgInstanciaFija instancia = new JDlgInstanciaFija(null, true);
                        this.setVisible(false);
                        instancia.setLocationRelativeTo(null);
                        instancia.setVisible(true);  
                        evaluacion = new Evaluacion
                        (
                                this.CboTipoEval.getSelectedItem().toString(),
                                porcentaje,
                                this.CboInstancia.getSelectedItem().toString()
                        );
                        evaluacion.agregarInstancias(instancia.getInstancias());
                        JOptionPane.showMessageDialog(rootPane, "Instancias agregadas!");                        
                    }
                    else {
                        evaluacion = new Evaluacion
                        (
                                this.CboTipoEval.getSelectedItem().toString(),
                                porcentaje,
                                this.CboInstancia.getSelectedItem().toString()
                        ); 
                        this.setVisible(false);
                    }                     
                }
                else {
                    JOptionPane.showMessageDialog(rootPane, "Porcentaje inválido!");                    
                }
            } 
            catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Porcentaje inválido!");                
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Falta información!");
        }
    }//GEN-LAST:event_BtnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgEvaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgEvaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgEvaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgEvaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgEvaluacion dialog = new JDlgEvaluacion(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JComboBox CboInstancia;
    private javax.swing.JComboBox CboTipoEval;
    private javax.swing.JLabel LabelPorcentaje;
    private javax.swing.JLabel LabelTipoEval;
    private javax.swing.JLabel LabelTipoInstancia;
    private javax.swing.JTextField TxtPorcentaje;
    // End of variables declaration//GEN-END:variables
}
