/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.sql.Profesor;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author usuario
 */
public class JFPrincipal extends javax.swing.JFrame {

    
    DefaultComboBoxModel modelGrupos;
    
    /**
     * Creates new form JFLogin
     */
    public JFPrincipal() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/view/source/favicon.ico")).getImage());
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno = new ImageIcon(this.getClass().getResource("/view/source/fondo.jpg"));
        JLabel fondo = new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());        
    }
    
    public void cargarGrupos(String pUsuario) throws SQLException {
        this.modelGrupos = new DefaultComboBoxModel();
        this.modelGrupos.addElement("");
        ArrayList<String> grupos = Profesor.getInstance().gruposProfesor(pUsuario);
        for (String grupo : grupos) {
            this.modelGrupos.addElement(grupo);
        }
        this.jCBGrupos.setModel(modelGrupos);
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnRegistrarNotas2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TxtUsuario = new javax.swing.JTextField();
        PwdClave = new javax.swing.JPasswordField();
        BtnEntrar = new javax.swing.JButton();
        jCBGrupos = new javax.swing.JComboBox();
        jBtnDiseñar = new javax.swing.JButton();
        jBtnRegistrar = new javax.swing.JButton();
        jBtnReportar = new javax.swing.JButton();

        jBtnRegistrarNotas2.setText("Registrar Notas");
        jBtnRegistrarNotas2.setEnabled(false);
        jBtnRegistrarNotas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegistrarNotas2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal - Registro de Notas - ");
        setResizable(false);

        TxtUsuario.setText("Usuario");
        TxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsuarioActionPerformed(evt);
            }
        });

        PwdClave.setText("123");

        BtnEntrar.setText("Acceder");
        BtnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEntrarActionPerformed(evt);
            }
        });

        jCBGrupos.setEnabled(false);

        jBtnDiseñar.setText("Diseñar Evaluación");
        jBtnDiseñar.setEnabled(false);
        jBtnDiseñar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDiseñarActionPerformed(evt);
            }
        });

        jBtnRegistrar.setText("Registrar Notas");
        jBtnRegistrar.setEnabled(false);
        jBtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegistrarActionPerformed(evt);
            }
        });

        jBtnReportar.setText("Enviar Reportes");
        jBtnReportar.setEnabled(false);
        jBtnReportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnReportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PwdClave, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnEntrar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jBtnDiseñar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCBGrupos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnReportar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PwdClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnEntrar))
                        .addGap(37, 37, 37)
                        .addComponent(jCBGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jBtnDiseñar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnRegistrar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnReportar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEntrarActionPerformed
        String usuario = TxtUsuario.getText();
        String clave = String.valueOf(PwdClave.getPassword());
        try {
            if (Profesor.getInstance().login(usuario, clave)) {
                cargarGrupos(usuario);
                this.TxtUsuario.setText("");
                this.PwdClave.setText("");
                this.jCBGrupos.setEnabled(true);
                this.jBtnDiseñar.setEnabled(true);  
                this.jBtnRegistrar.setEnabled(true); 
                this.jBtnReportar.setEnabled(true);          
            } 
            else {
                JOptionPane.showMessageDialog(rootPane, "Acceso inválido.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnEntrarActionPerformed


    private void TxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsuarioActionPerformed

    private void jBtnDiseñarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDiseñarActionPerformed
        if (this.jCBGrupos.getSelectedIndex() != 0) {
            JDlgDiseño vistaT = new JDlgDiseño(null, true);
            this.setVisible(false);
            try {
                vistaT.setCodigoGrupo(jCBGrupos.getSelectedItem().toString());
                vistaT.cargarEvaluaciones();
            } catch (SQLException ex) {
                Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            vistaT.setLocationRelativeTo(null);
            vistaT.setVisible(true);
            this.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Seleccione un Grupo!");
        }  
    }//GEN-LAST:event_jBtnDiseñarActionPerformed

    private void jBtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegistrarActionPerformed
         if (this.jCBGrupos.getSelectedIndex() != 0) {
            this.setVisible(false);
            JDlgRegistro registro = new JDlgRegistro(null, true);
            try {
                registro.setCodigoGrupo(jCBGrupos.getSelectedItem().toString());
                registro.cargarEstudiantes();
                registro.cargarEvaluaciones();
                registro.inicializarNotas();
            } catch (SQLException ex) {
                Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            registro.setLocationRelativeTo(null);
            registro.setVisible(true);
            this.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Seleccione un Grupo!");
        }
    }//GEN-LAST:event_jBtnRegistrarActionPerformed

    private void jBtnRegistrarNotas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegistrarNotas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnRegistrarNotas2ActionPerformed

    private void jBtnReportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReportarActionPerformed
         if (this.jCBGrupos.getSelectedIndex() != 0) {
            this.setVisible(false);
            JDlgReporte reporte = new JDlgReporte(null, true);
            try {
                reporte.setCodigoGrupo(jCBGrupos.getSelectedItem().toString());
                reporte.cargarEstudiantes();
            } catch (SQLException ex) {
                Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            reporte.setLocationRelativeTo(null);
            reporte.setVisible(true);
            this.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Seleccione un Grupo!");
        }
    }//GEN-LAST:event_jBtnReportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnEntrar;
    public javax.swing.JPasswordField PwdClave;
    public javax.swing.JTextField TxtUsuario;
    private javax.swing.JButton jBtnDiseñar;
    private javax.swing.JButton jBtnRegistrar;
    private javax.swing.JButton jBtnRegistrarNotas2;
    private javax.swing.JButton jBtnReportar;
    private javax.swing.JComboBox jCBGrupos;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
