sqlcmd -s localhost -i C:\SQLScripts_Proyecto1\RegistroNotas.sql
sqlcmd -s localhost -i C:\SQLScripts_Proyecto1\llenado.sql
sqlcmd -s localhost -i C:\SQLScripts_Proyecto1\functions\curso.sql
sqlcmd -s localhost -i C:\SQLScripts_Proyecto1\functions\estudiante.sql
sqlcmd -s localhost -i C:\SQLScripts_Proyecto1\functions\grupo.sql
sqlcmd -s localhost -i C:\SQLScripts_Proyecto1\functions\instancia.sql
sqlcmd -s localhost -i C:\SQLScripts_Proyecto1\functions\evaluacion.sql
sqlcmd -s localhost -i C:\SQLScripts_Proyecto1\functions\miembro.sql
sqlcmd -s localhost -i C:\SQLScripts_Proyecto1\functions\periodo.sql
sqlcmd -s localhost -i C:\SQLScripts_Proyecto1\functions\profesor.sql
sqlcmd -s localhost -i C:\SQLScripts_Proyecto1\functions\tipoevaluacion.sql
sqlcmd -s localhost -i C:\SQLScripts_Proyecto1\storeprocedures\curso.sql
sqlcmd -s localhost -i C:\SQLScripts_Proyecto1\storeprocedures\estudiante.sql
sqlcmd -s localhost -i C:\SQLScripts_Proyecto1\storeprocedures\evaluacion.sql
sqlcmd -s localhost -i C:\SQLScripts_Proyecto1\storeprocedures\grupo.sql
sqlcmd -s localhost -i C:\SQLScripts_Proyecto1\storeprocedures\miembro.sql
sqlcmd -s localhost -i C:\SQLScripts_Proyecto1\storeprocedures\periodo.sql
sqlcmd -s localhost -i C:\SQLScripts_Proyecto1\storeprocedures\profesor.sql
sqlcmd -s localhost -i C:\SQLScripts_Proyecto1\storeprocedures\tipoevaluacion.sql